// Diagnostics codes used by the component provider
export const Codes = {
  PRECONDITION_REQUIRED: 'PRECONDITION_REQUIRED',
  PRECONDITION_INVALID: 'PRECONDITION_INVALID',
  AGENT_REGISTRATION_FAILED: 'AGENT_REGISTRATION_FAILED',
  AGENT_SOCKET_ERROR: 'AGENT_SOCKET_ERROR',
};
